------------------------------------
-- EasyAdmin: Integrity Check
--
-- Verifies that resource files match the hashes recorded at build time.
-- The hash file (.ea_integrity.json) is generated by scripts/generate-integrity.py
-- during the release workflow and is NOT committed to git.
--
-- FAIL-CLOSED design:
--   The EasyAdminIntegrity global is initialised as "failed" below.
--   Only a successful check flips it to "passed".
--   If this file is deleted entirely, the global is never defined
--   and the consumer (server/core/runtime.lua) treats that as failure.
--
-- SHA-256 implementation is self-contained (pure Lua, no external deps).
------------------------------------

-- Default: FAILED. Only set to passed if the check completes successfully.
EasyAdminIntegrity = {
    checked = false,
    passed = false,
    totalFiles = 0,
    missingFiles = {},
    modifiedFiles = {},
}

-- ============================================================
-- SHA-256 (pure Lua, RFC 4634 compliant)
-- ============================================================

local function leftRotate(x, n)
    return bit32.rshift(x, 32 - n) + bit32.band(x, bit32.lshift(1, n) - 1)
end

local function sha256(message)
    local K = {
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5,
        0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
        0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
        0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
        0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc,
        0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
        0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
        0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
        0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
        0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
        0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3,
        0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
        0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5,
        0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
        0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
    }

    local msg = message
    local origLenBits = #msg * 64 + (#msg * 8)

    -- Padding
    msg = msg .. "\x80"
    while (#msg * 8) % 512 ~= 448 do
        msg = msg .. "\x00"
    end

    -- Append original length as 64-bit big-endian
    local hi = math.floor(origLenBits / 2^32)
    local lo = origLenBits % 2^32
    msg = msg .. string.char(
        bit32.rshift(hi, 24) % 256, bit32.rshift(hi, 16) % 256,
        bit32.rshift(hi, 8) % 256, hi % 256,
        bit32.rshift(lo, 24) % 256, bit32.rshift(lo, 16) % 256,
        bit32.rshift(lo, 8) % 256, lo % 256
    )

    -- Initial hash values
    local h0, h1, h2, h3, h4, h5, h6, h7 =
        0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
        0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19

    -- Process each 512-bit (64-byte) block
    for offset = 1, #msg, 64 do
        local W = {}

        -- Prepare message schedule
        for i = 0, 15 do
            local b = offset + i * 4
            W[i] = bit32.bor(
                bit32.lshift(string.byte(msg, b + 1) or 0, 24),
                bit32.lshift(string.byte(msg, b + 2) or 0, 16),
                bit32.lshift(string.byte(msg, b + 3) or 0, 8),
                string.byte(msg, b + 4) or 0
            )
        end

        for i = 16, 63 do
            local s0 = leftRotate(W[i - 15], 7) + leftRotate(W[i - 15], 18) + bit32.rshift(W[i - 15], 3)
            local s1 = leftRotate(W[i - 2], 17) + leftRotate(W[i - 2], 19) + bit32.rshift(W[i - 2], 10)
            W[i] = bit32.add(bit32.add(bit32.add(W[i - 16], s0), W[i - 7]), s1)
        end

        local a, b, c, d, e, f, g, h = h0, h1, h2, h3, h4, h5, h6, h7

        for i = 0, 63 do
            local S1 = leftRotate(e, 6) + leftRotate(e, 11) + leftRotate(e, 25)
            local ch = bit32.bor(bit32.band(e, f), bit32.band(bit32.bnot(e), g))
            local temp1 = bit32.add(bit32.add(bit32.add(bit32.add(h, S1), ch), K[i + 1]), W[i])
            local S0 = leftRotate(a, 2) + leftRotate(a, 13) + leftRotate(a, 22)
            local maj = bit32.bor(bit32.bor(bit32.band(a, b), bit32.band(a, c)), bit32.band(b, c))
            local temp2 = bit32.add(S0, maj)

            h = g
            g = f
            f = e
            e = bit32.add(d, temp1)
            d = c
            c = b
            b = a
            a = bit32.add(temp1, temp2)
        end

        h0 = bit32.add(h0, a)
        h1 = bit32.add(h1, b)
        h2 = bit32.add(h2, c)
        h3 = bit32.add(h3, d)
        h4 = bit32.add(h4, e)
        h5 = bit32.add(h5, f)
        h6 = bit32.add(h6, g)
        h7 = bit32.add(h7, h)
    end

    local digest = string.format("%08x%08x%08x%08x%08x%08x%08x%08x",
        h0, h1, h2, h3, h4, h5, h6, h7)
    return digest
end

-- ============================================================
-- Integrity check logic
-- ============================================================

local resourceName = GetCurrentResourceName()
local integrityPath = ".ea_integrity.json"

local function loadIntegrityData()
    local raw = LoadResourceFile(resourceName, integrityPath)
    if not raw then
        return nil
    end
    local ok, data = pcall(json.decode, raw)
    if not ok then
        return nil
    end
    return data
end

function RunIntegrityCheck()
    local data = loadIntegrityData()

    if not data or not data.files then
        -- No hash file — dev build or stripped release
        EasyAdminIntegrity.checked = true
        EasyAdminIntegrity.passed = false
        EasyAdminIntegrity.missingHashFile = true
        print("^3[EasyAdmin] ^7Integrity hash file not found — running unverified build (no integrity check)")
        return
    end

    local files = data.files
    local total = 0
    local missing = {}
    local modified = {}

    for filePath, expectedHash in pairs(files) do
        total = total + 1
        local content = LoadResourceFile(resourceName, filePath)

        if not content then
            table.insert(missing, filePath)
        else
            local actualHash = sha256(content)
            if actualHash ~= expectedHash then
                table.insert(modified, filePath)
            end
        end
    end

    EasyAdminIntegrity.checked = true
    EasyAdminIntegrity.totalFiles = total
    EasyAdminIntegrity.missingFiles = missing
    EasyAdminIntegrity.modifiedFiles = modified
    EasyAdminIntegrity.passed = (#missing == 0 and #modified == 0)

    if EasyAdminIntegrity.passed then
        PrintDebugMessage(string.format("Integrity check passed — %d file(s) verified", total), 4)
    else
        -- Debug: list every file that failed (loglevel 2 = warning)
        if #modified > 0 then
            local modifiedList = table.concat(modified, ", ")
            PrintDebugMessage(string.format("Integrity check: %d file(s) modified: %s", #modified, modifiedList), 2)
        end
        if #missing > 0 then
            local missingList = table.concat(missing, ", ")
            PrintDebugMessage(string.format("Integrity check: %d file(s) missing: %s", #missing, missingList), 2)
        end

        print("")
        print("^1[EasyAdmin] ^3! INTEGRITY CHECK FAILED !^7")
        print("")

        if #modified > 0 then
            print("^1  Modified files:^7")
            for _, f in ipairs(modified) do
                print("^1    -^7 " .. f)
            end
            print("")
        end

        if #missing > 0 then
            print("^1  Missing files:^7")
            for _, f in ipairs(missing) do
                print("^1    -^7 " .. f)
            end
            print("")
        end

        print("^3  EasyAdmin has been modified from its original release.^7")
        print("^3  No support will be provided for modified builds.^7")
        print("^3  Download a clean release from:^7")
        print("^3  https://github.com/Blumlaut/EasyAdmin/releases^7")
        print("")
    end
end

-- Run the check once on resource start
-- Wrapped in Citizen.CreateThread so it doesn't block resource startup
Citizen.CreateThread(function()
    -- Small delay to let other init finish and not interleave with splash
    Wait(500)
    RunIntegrityCheck()
end)

-- Export for external checks
exports('getIntegrityStatus', function()
    return EasyAdminIntegrity
end)
